# Site title
title: Blog van Eva Claessen

# Tagline below the site title on post list pages
tagline: De wereld door Russische ogen.

# A description of your site for social meta tag, search engines, and feed.xml
description:

# The base hostname & protocol of your site for where absolute urls are needed
url: "http://localhost:4000"

# The site cover image on the home page
image: /images/site-image.jpg

# The shortname for your Disqus site to enable comments
disqus_shortname: evaclaessen

# Your Google Analytics tracking code
google_analytics_tracking_id: UA-75058506-1


# Site navigation
nav:
  - title: "Home"
    url:   "/"
  - title: "Over mij"
    url:   "/over"
  - title: "Contact"
    url: "/contact"


# The links in the site footer
footer_links:
  - title: "RSS"
    url:   "/feed.xml"
  - title: "Privacy policy"
    url:   "/privacy_policy"

# Extra Open Graph and Twitter Cards settings for social sharing

# Fallback og:image when no page.image or site.image. Facebook requires image be
# at least 200 x 200 pixels.
og_image:

# twitter:site. Your Twitter username without "@"
twitter_site: evaclaessen


# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: page/:num/
gems: [jekyll-paginate]

permalink: /:title/
markdown: kramdown
kramdown:
  input: GFM

exclude:
    - node_modules

sass:
  style: compressed